# mRISC-I simulator testsuite.

if {! $sidtarget(mt)} { untested "hw-cpu-mt not available"; return }

# Load a baseboard description for SID simulators.
load_base_board_description "basic-sid"

# load support procs (none yet)
load_lib "cpudefs.exp"

# all machines
set all_machs "mt"

# Add --nosched to the flags to supress scheduling restrictions.
set gas_flags "--gdwarf2 --nosched"

# Run the tests
run-sid-tests-raw mt-elf mt $srcdir/sidcomp.cgen-cpu.mt "*.s" $gas_flags "" "" mt-gloss.conf x
