@c Copyright (C) 2000 Red Hat, Inc.
@c This file is part of the CGEN manual.
@c For copying conditions, see the file cgen.texi.

@node Credits
@chapter Credits

The following people, listed in alphabetical order, have helped in their own
way.  Thanks!

@itemize @minus
@item Dave Brolley
@item Andrew Cagney
@item Steve Chamberlain
@item Nick Clifton
@item Bob Cmelik
@item Frank Ch. Eigler
@item Ben Elliston
@item Kim Knuttila
@item Ken Raeburn
@item Jim Wilson
@end itemize

There's a TV program I watched growing up called ``The Hilarious House
Of Frightenstein''.  The credits at the end had a twist in that Billy
Van, who played most of the characters, appeared in them again and
again.  I would do the same here for Ian Lance Taylor.
