@c Copyright (C) 2000, 2010 Red Hat, Inc.
@c This file is part of the CGEN manual.
@c For copying conditions, see the file cgen.texi.

@node Credits
@chapter Credits

The following people, listed in alphabetical order, have contributed to
CGEN in their own way--thanks!  If you feel your name has been wrongly
omitted from this list, please contact one of the maintainers.

@itemize @minus
@item Dave Brolley
@item Andrew Cagney
@item Steve Chamberlain
@item Nick Clifton
@item Bob Cmelik
@item Frank Ch. Eigler
@item Ben Elliston
@item Matthew Green
@item Kim Knuttila
@item Greg McGary
@item Ken Raeburn
@item Ian Lance Taylor
@item Jim Wilson
@end itemize
