#! /bin/sh
# Utility script to generate html docs for all ports.

# Run this script in the src/cgen directory.

# Exit on any error.
set -e

# For debugging.
set -x

# ??? Some are missing, need to add them after some research.
archs="arm frv i960 m32r openrisc xstormy16"

rm -rf /tmp/tmp-cgen-doc
mkdir /tmp/tmp-cgen-doc

export cgendir=`pwd`

(
  set -e
  set -x
  cd /tmp/tmp-cgen-doc
  $cgendir/configure --prefix /tmp/junk --target m32r-elf

  for a in $archs
  do
    make html ARCH=$a
  done
)
