# Run a monkey test on the components in this component library. 

load_lib "monkey.exp"

set types [list \
	       2way/256kb/16/fifo \
	       basic 4way/8kb/64/lru \
	       full/64kb/32/random \
	       direct/16kb/128 ]

foreach type $types {
    proc state_safe_p {} { return 0 }
    proc attr_safe_p {attr} { return [expr ![string match $attr dump!]] }

    monkey_test hw-cache-$type cache_component_library libcache.la
}
