# Run a monkey test on the components in this component library. 

load_lib "monkey.exp"

if {! $sidtarget(arm)} then { untested "hw-interrupt-arm/ref not available"; return }
monkey_test hw-interrupt-arm/ref interrupt_component_library libinterrupt.la

if {! $sidtarget(arm)} then { untested "hw-interrupt-cogent/cma222 not available"; return }
monkey_test hw-interrupt-cogent/cma222 interrupt_component_library libinterrupt.la
